#!/bin/bash
# Helper for building source packages for uploading to a PPA
#
# Author : Lekensteyn <lekensteyn@gmail.com>
# License: GPLv3+

DISTS=(precise trusty)

cd "$(dirname "$(dirname "$(readlink -f "$0")")")"
distsdir="$PWD"

pkg="$1"
tarball="$2"
ballname="${2##*/}"
version="${ballname%%.orig.tar.gz}"
version="${version##*_}"
while :; do
    for dist in "${DISTS[@]}"; do
        [ -d "$dist/$pkg/debian" ] && break 2
    done
    echo "Unknown package: $pkg"
    echo "Not known by dists: ${DISTS[*]}"
    echo "Usage: $0 package-name path/to/package-name_version.orig.tar.gz"
    exit 2
done

if [[ $ballname != ${pkg}_*.orig.tar.gz ]]; then
    echo "Invalid tarball: $tarball, expecting something like:"
    echo "Usage: $0 $pkg path/to/${pkg}_version.orig.tar.gz"
    exit 2
fi
if [ ! -f "$tarball" ]; then
    echo "Tarball $tarball does not exist."
    exit 2
fi

tobuild=()
versions=()

for dist in "${DISTS[@]}"; do
    [ -s "$dist/$pkg/debian/changelog" ] || continue
    dist_version="$(head -1 "$dist/$pkg/debian/changelog" \
        | cut -d')' -f1 | cut -d'(' -f2)"
    while :; do
        read -p "Build $pkg $dist_version for $dist? (y/n) " yn
        case "$yn" in
          [Yy]*) break ;;
          [Nn]*) continue 2;;
        esac
    done
    tobuild[${#tobuild[@]}]="$dist"
    versions[${#versions[@]}]="$dist_version"
done

if [ ${#tobuild[@]} -eq 0 ]; then
    echo "No dists selected, exiting."
    exit 3
fi

tmpdir="$(mktemp -d)"
pkgdir="$tmpdir/${pkg}-${version}"
cp -v "$tarball" "$tmpdir/$ballname"
mkdir "$pkgdir"
cd "$pkgdir"
tar xf "$tmpdir/$ballname" --strip-components=1
for dist in "${tobuild[@]}"; do
    echo "Building for $dist..."
    rm -rf "$pkgdir/debian"
    cp -r "$distsdir/$dist/$pkg/debian" "$pkgdir/debian"
    debuild -S
done

tobeuploaded=()
for pkg_version in "${versions[@]}"; do
    tobeuploaded[${#tobeuploaded[@]}]="${pkg}_${pkg_version}_source.changes"
done
cd "$tmpdir"
ls -l "${tobeuploaded[@]}"
echo "Please check if the packages work and then publish them:"
echo "cd $tmpdir"
echo "dput ppa:bumblebee/testing ${tobeuploaded[*]}"
