#!/bin/bash

set -e

if [ "$#" -ne 2 ]; then
    echo "Usage: update-drivers <previous_version> <new_version>"
    exit 1
fi

for dist in precise trusty vivid wily xenial
do
    sed -i "s/nvidia-experimental-$1/nvidia-experimental-$1 |\n nvidia-$2 | nvidia-$2-updates | nvidia-experimental-$2/g" $dist/bumblebee/debian/control
    echo "# $2" >> $dist/bumblebee/debian/bumblebee.conf
    echo "blacklist nvidia-$2" >> $dist/bumblebee/debian/bumblebee.conf
    echo "blacklist nvidia-$2-updates" >> $dist/bumblebee/debian/bumblebee.conf
    echo "blacklist nvidia-experimental-$2" >> $dist/bumblebee/debian/bumblebee.conf
done
