#!/bin/sh
# postinst script for bumblebee
#
# see: dh_installdeb(1)

set -e

case "$1" in
  configure)
    # perhaps this section can be retrieved from stages/ubuntu/configure?
    if ! grep -rqE "^ *blacklist +nouveau\b" /etc/modprobe.d; then
        echo "blacklist nouveau" >> /etc/modprobe.d/nouveau-blacklist.conf
    fi
    NVIDIABUSID=$(lspci -d 10de: -n | grep '030[02]:' | cut -d' ' -f1 | tr . :)
    re_busid='^( *BusID +")[^"]*'

    sed -E -i /etc/bumblebee/xorg.conf.nvidia -e "s,$re_busid,\1$NVIDIABUSID,"
    groupadd bumblebee || true

    # Repair GL on the intel display
    for arch in x86_64-linux-gnu i386-linux-gnu; do
        update-alternatives --force --set \
            ${arch}_gl_conf /usr/lib/$arch/mesa/ld.so.conf 2>/dev/null || true
    done

    # versions before Oneiric without multiarch
    update-alternatives --force --set \
        gl_conf /usr/lib/mesa/ld.so.conf 2>/dev/null || true

    ldconfig

    update-rc.d bumblebee defaults
    if [ -x /usr/sbin/invoke-rc.d ]; then
        invoke-rc.d bumblebee start
    else
        /etc/init.d/bumblebee start
    fi
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
