#!/bin/sh
# postinst script for bumblebee
#
# see: dh_installdeb(1)

set -e

case "$1" in
  configure)
    # perhaps this section can be retrieved from stages/ubuntu/configure?
    if ! grep -rqE "^ *blacklist +nouveau\b" /etc/modprobe.d; then
        echo "blacklist nouveau" >> /etc/modprobe.d/nouveau-blacklist.conf
    fi
    NVIDIABUSID=$(lspci -d 10de: -n | grep '030[02]:' | cut -d' ' -f1 | tr . :)
    re_busid='^( *BusID +")[^"]*'

    sed -E -i /etc/bumblebee/xorg.conf.nvidia -e "s,$re_busid,\1$NVIDIABUSID,"
    groupadd bumblebee || true

    # Repair GL on the intel display

    # Multiarch X server on a 32bit Ubuntu does not have a x86_64 mesa ld.so
    ARCH=$(uname -m)
    X_ARCH=i386-linux-gnu
    if [ "$ARCH" = 'x86_64' ]; then
        X_ARCH="$X_ARCH x86_64-linux-gnu"
    fi

    for arch in $X_ARCH; do
        # check if the link exist to prevent error messages
        if update-alternatives --list ${arch}_gl_conf >/dev/null 2>&1; then
            update-alternatives --force --set ${arch}_gl_conf /usr/lib/$arch/mesa/ld.so.conf
        fi
    done

    # versions before Oneiric without multiarch
    if update-alternatives --list gl_conf >/dev/null 2>&1; then
        update-alternatives --force --set gl_conf /usr/lib/mesa/ld.so.conf
    fi

    ldconfig

    update-rc.d bumblebee defaults
    if [ -x /usr/sbin/invoke-rc.d ]; then
        invoke-rc.d bumblebee start
    else
        /etc/init.d/bumblebee start
    fi
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
