#!/bin/sh
# postrm script for bumblebee
#
# see: dh_installdeb(1)

set -e

rm_conffile() {
    local PKGNAME="$1" # Unused
    local CONFFILE="$2"

    if [ -f "$CONFFILE".dpkg-del ]; then
        mv -f "$CONFFILE".dpkg-del "$CONFFILE"
    fi
}

case "$1" in
  purge)
    groupdel bumblebee || true
    for file in bumblebee.conf xorg.conf.nvidia xorg.conf.nouveau; do
        rm -f /etc/bumblebee/$file
    done
    ;;
  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

case "$1" in
  abort-install|abort-upgrade)
    if dpkg --compare-versions "$2" le 2.4.2; then
        rm_conffile bumblebee /etc/bumblebee/bumblebee.conf
        rm_conffile bumblebee /etc/bumblebee/xorg.conf.nvidia
        rm_conffile bumblebee /etc/bumblebee/xorg.conf.nouveau
    fi
    ;;
esac
#DEBHELPER#

exit 0
