#!/bin/sh
# postinst script for bumblebee
#
# see: dh_installdeb(1)

set -e

rm_conffile() {
    local PKGNAME="$1" # Unused
    local CONFFILE="$2"
    if [ -f "$CONFFILE".dpkg-del ]; then
        rm -f "$CONFFILE".dpkg-del
    fi
}

case "$1" in
  configure)
    groupadd bumblebee || true
    for file in bumblebee.conf xorg.conf.nvidia xorg.conf.nouveau; do
        if [ ! -f /etc/bumblebee/$file ]; then
            cp -p /usr/share/bumblebee/default-conf/$file /etc/bumblebee/
        fi
    done
    if dpkg --compare-versions "$2" le 2.4.2; then
        rm_conffile bumblebee /etc/bumblebee/bumblebee.conf
        rm_conffile bumblebee /etc/bumblebee/xorg.conf.nvidia
        rm_conffile bumblebee /etc/bumblebee/xorg.conf.nouveau
    fi
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
