#!/bin/sh
# preinst script for bumblebee
#
# see: dh_installdeb(1)

set -e

# Remove a no-longer used conffile
rm_conffile() {
    local PKGNAME="$1"
    local CONFFILE="$2"

    [ -e "$CONFFILE" ] || return 0

    local md5sum="$(md5sum $CONFFILE | sed -e 's/ .*//')"
    local old_md5sum="$(dpkg-query -W -f='${Conffiles}' $PKGNAME | \
            sed -n -e "\' $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
    if [ "$md5sum" != "$old_md5sum" ]; then
        echo "Obsolete conffile $CONFFILE has been modified by you."
        echo "Saving as $CONFFILE.dpkg-bak ..."
        mv -f "$CONFFILE" "$CONFFILE".dpkg-bak
    else
        echo "Removing obsolete conffile $CONFFILE ..."
        rm -f "$CONFFILE"
    fi
}

case "$1" in
  install|upgrade)
    # check for ancient versions
    if [ -f /etc/bumblebee ]; then
        cat >&2 <<MSG
An ancient installation of MrMEEE/bumblebee or mj-casalogic/bumblebee has been
detected. To prevent damage, the installation of this version won't be
continued. If you are a novice, you are recommended to reinstall Ubuntu.
MSG
        exit 1
    fi
    if dpkg --compare-versions "$2" le 2.4.2; then
        rm_conffile bumblebee /etc/bumblebee/bumblebee.conf
        rm_conffile bumblebee /etc/bumblebee/xorg.conf.nvidia
        rm_conffile bumblebee /etc/bumblebee/xorg.conf.nouveau
    fi
    ;;

  abort-upgrade)
    ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
