#!/bin/sh
# postinst script for bumblebee
#
# see: dh_installdeb(1)

set -e

case "$1" in
  configure)
    groupadd bumblebee || true
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
