#!/bin/sh
# prerm script for bumblebee
#
# see: dh_installdeb(1)

set -e

case "$1" in
  remove|upgrade|deconfigure)
    [ -x /etc/init.d/bumblebee ] && /etc/init.d/bumblebee stop || true
    ;;

  failed-upgrade)
    ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
